Adding SHA-256 and SHA-512 password hashing support via CRYPT
gosa-project/gosa-core pull request #15
Opened 2018-08-10 18:49 UTC by tmack0

This PR adds support for SHA-256 and SHA-512 password hashing via CRYPT, both of which are supported by any modern openldap server (and probably any other ldap server using standard CRYPT libs).

2018-08-15 10:28 UTC, sunweaver reviewed
Looks ok (without having checked the actual crypto mechs). @master-caster: are you familiar with crypt hashing OTOYH? Please review.

2018-08-15 10:54 UTC, master-caster requested changes
Hallo and thank you for your pull request,

it looks like "crypt/sha512" is already included with 
another salt length in method "generate_hash". With this implementation 
you can not choose between the salt length.

Since $salt isn't used anywhere i may drop the "crypt/sha512" with a salt length of 8. 

In the other methods the "crypt/sha512" blocks are complete duplicates.

2018-08-15 19:03 UTC, tmack0 commented
Looks like I pasted my code diff without checking the upstream I was pasting to first for this one. 
The version I was running didn't have this yet.
I will update to remove dupes and only include salt length 16.

2018-08-20 05:54 UTC, master-caster approved these changes
Looks good to me

2018-08-20 05:54 UTC, merged