Native ntlm passwords
gosa-project/gosa-core pull request #17
Opened 2018-08-15 00:23 UTC by tmack0

This PR uses native PHP to generate the NTLM and LM hashes. It also only generates a valid LM hash if the sambaHashHook config item is set specifically to "LM" since this hashing method is extremely old and broken, with full rainbow tables well known, that could weaken/compromise passwords stored using it. Most legacy things needing it should support NTLM which is better, and as such only junk will be returned unless LM hashing is specifically requested. Note that the sambaHashHook config field itself is only checked for empty/not-empty to determine if samba password manipulation should be enabled. It does not use the field to store an external command.
This replaces the need to spawn a shell and run perl, which required shell escaping/base64 encoding passwords.

2018-08-15 10:24 UTC, sunweaver requested changes
I added some comments to this PR, please give some feedback. I also will request a review from the GONICUS dev that maintains GOsa 2.7.x branch.

2018-08-15 10:24 UTC, sunweaver commented on include/functions.inc
> +    $iv = mcrypt_create_iv($is, MCRYPT_RAND);
All of gosa-core just add mcrypt dependencies removed everywhere, please drop the mcrypt part.

2018-08-15 10:24 UTC, sunweaver commented on contrib/gosa.conf.5
> +method is ancient, broken, and rainbow tables exist for all passwords to it. IFF it
IFF -> typo?

2018-08-15 10:24 UTC, sunweaver commented on contrib/gosa.conf.5
> +if its empty, not empty, or contains "LM". Safe default: "YES" or leave blank.
why not?: empty, NT or NTLM?

2018-08-15 10:24 UTC, sunweaver commented
@master-caster: please take a look at this PR when time allows... Thanks, Mike.

2018-08-15 18:29 UTC, tmack0 commented on contrib/gosa.conf.5
> +if its empty, not empty, or contains "LM". Safe default: "YES" or leave blank.
Will update. Suggested field values empty, "NTLM", "NTLM+LM" for samba disabled, NTLM Only, NTLM and LM hashes. Will bump the conditional to the new value.

2018-08-15 18:29 UTC, tmack0 commented on contrib/gosa.conf.5
> +method is ancient, broken, and rainbow tables exist for all passwords to it. IFF it
If and only if.

2018-08-15 18:29 UTC, tmack0 commented on include/functions.inc
> +    $iv = mcrypt_create_iv($is, MCRYPT_RAND);
Done.

2018-08-20 06:35 UTC, master-caster reviewed
This PR looks good to me.

I need to check some gosa installations on this.

2018-08-20 08:48 UTC, master-caster approved these changes

2018-08-20 08:48 UTC, merged